### ISSUE TITLE
Package importing issue in Jupiter Lab python interface

### ISSUE THREAD

**Issue by Mohammad-Keyhani** [ghodsizadeh/tehran-stocks#1]
When I import your designed package in Jupiter Lab 0.34.9 interface of 1.9.2 anaconda navigator, this error has resulted:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-8e04d842786d> in <module>()
----> 1 import tehran_stocks

~\Anaconda3\lib\site-packages\tehran_stocks\__init__.py in <module>()
      1 import os
      2 
----> 3 import tehran_stocks.config as db
      4 from tehran_stocks.download import (
      5     get_all_price,

ModuleNotFoundError: No module named 'tehran_stocks.config'

please see why this issue has happened?
Thanks

**Comment by ghodsizadeh** [comment]
Thanks for noticing. 
It was a problem with the packaging. 
You can install the package using `conda install -c ghodsizadeh tehran_stocks` or 'pip install --upgrade tehran_stocks` is now on version `0.5.6`.

Please tell me if you have a problem after using `conda` for installation.

**Comment by Mohammad-Keyhani** [comment]
Regrettably, I couldn't launch the package not manually or by pip and conda syntaxes. I tried many times with python 3.6 IDLE and Anaconda main core interface. Do you ever run your package in a third party PC? Errors are described bellow:

**Anaconda's error:**
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-8e04d842786d> in <module>()
----> 1 import tehran_stocks

ModuleNotFoundError: No module named 'tehran_stocks'

**Error in Python 3.6:**
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tehran_stocks
ModuleNotFoundError: No module named 'tehran_stocks'

**Also using conda syntax returns this error:** 
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tehran_stocks

Current channels:

  - https://conda.anaconda.org/ghodsizadeh/win-32
  - https://conda.anaconda.org/ghodsizadeh/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

However, maybe I just do it in the wrong way?, so I strongly suggest to make a video about this package functionality and installation, thank you so much for your good job. 
Hope to hear good news!

**Comment by ghodsizadeh** [comment]
Maybe that's because I didn't upload `noarch` and `win32` version of the package on conda repo.
I just upload them. Please test again and tell me the result.
I'll try to test the code on a windows PC and anaconda environment as soon as possible.
And thanks for the video Idea, I'll try to make that video very soon.
