### ISSUE TITLE
Adjusted stock prices

### ISSUE THREAD

**Issue by accesstoken** [ghodsizadeh/tehran-stocks#16]
Hey @ghodsizadeh,
Great job!
I was wondering if it is possible to get the **adjusted** stock prices as well.

**Comment by ghodsizadeh** [comment]
Impossible is Impossible. :)
But adding adjusted price is a little bit complicated. If you know a (readable)source that shows adjusted price or dividends, I (or even you) can add adjusted price to package.

**Comment by najafi82** [comment]
با سلام و احترام
مطمئن نیستم ولی فکر میکنم دسترسی به قیمتهای تعدیل شده تنها از طریق اکانت پرمیوم و پرداخت هزینه اشتراک امکانپذیر باشه

**Comment by ehsanSET** [comment]
> Impossible is Impossible. :)
> But adding adjusted price is a little bit complicated. If you know a (readable)source that shows adjusted price or dividends, I (or even you) can add adjusted price to package.

I think this project uses web scrapping. If you go to every company's history page, you see a column named yesterday and a column that is the price of the day. 
In normal days, yesterday price of today equals the price of yesterday. But when company increases capital or pays dividend these two differ.
Using the ratio of the above-mentioned values, one can adjust prices. Thanks

**Comment by a-Rahmati** [comment]
در صفحه‌ی هر نماد در سایت فناوری بورس یک دکمه‌ای هست به نام "اطلاعات تکمیلی" که یک گزینه دارد به نام "تعدیل قیمت". آنجا تمام تعدیلاتی که باید روی قیمت اعمال شود را نشان می‌دهد.

باید عدد کوچک را تقسیم بر عدد بزرگ کنیم تا یک ضریبی به دست بیاید. مثلاً این ضریب برای آخرین تعدیل کگل می‌شود:
16350÷17250=0.94782609
حالا باید همه‌ی قیمت‌هایی که قبل از تاریخ تعدیل بوده‌اند ضرب در این ضریب شوند.

**Comment by ghodsizadeh** [comment]
در نسخه جدید امکان دریافت موارد تعدیل قیمت وجود داره.
