### ISSUE TITLE
وجود نداشتن فایل config

### ISSUE THREAD

**Issue by ashkanjalaliQ** [ghodsizadeh/tehran-stocks#17]
من با سی ام دی این بسته رو نصب میکنم و توی نصب کردن مشکلی ندارم. ولی وقتی میخوام توی پایتون ازش استفاده کنم، میگه که فایل کانفیگ وجود نداره. اگر میشه یه راهنمایی بکنید

**Comment by ghodsizadeh** [comment]
میشه خطای مورد نظرتون رو کپی کنید تا بتونم بهتر بررسی کنم.

**Comment by ashkanjalaliQ** [comment]
میگه فایل کانفیگ وجود ندارد

**Comment by ghodsizadeh** [comment]
همون پیام رو اگر به صورت انگلیسی کپی پیست کنید. من راحتتر می‌تونم باگ رو پیگیری کنم.

**Comment by Nixuri** [comment]
![image](https://user-images.githubusercontent.com/20394645/73940742-4171e680-4901-11ea-95a6-03c120461936.png)

**Comment by ghodsizadeh** [comment]
به نسخه جدید بروزرسانی کنید و ببینید که باز هم این خطا وجود داره یا نه.
