### ISSUE TITLE
get_all_price failed with error

### ISSUE THREAD

**Issue by gr8linux** [ghodsizadeh/tehran-stocks#18]
When I try to run get_all_price it always stop with an error on sql

InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT stocks.code AS stocks_code 
FROM stocks 
WHERE stocks.group_code = ?]
[parameters: ((10,),)]
(Background on this error at: http://sqlalche.me/e/rvf5)

I run the miniconda vs pure python on ubuntu

**Comment by gr8linux** [comment]
I fix the issue in my own fork
https://github.com/ghodsizadeh/tehran-stocks

**Comment by ghodsizadeh** [comment]
It would be great if you create a pull request and merge it to the main repository and Pypi as well.

**Comment by gr8linux** [comment]
Merge already requested

**Comment by ghodsizadeh** [comment]
Thanks for your great contribution.
I merge your pull request.
But it would be better to make separate your pull request for each  feature or bug fix, it makes reviewing much faster and easier.
