### ISSUE TITLE
when i want to compile by VSCode

### ISSUE THREAD

**Issue by Mohamadmr** [ghodsizadeh/tehran-stocks#2]
### This error occurs when "import tehran_stocks" runs:

ModuleNotFoundError
No module named 'tehran_stocks.config'

File "D:\ ... \python\lib\site-packages\tehran_stocks\__init__.py", line 3, in <module>
    import tehran_stocks.config as db
ModuleNotFoundError: No module named 'tehran_stocks.config'

**Comment by ghodsizadeh** [comment]
Please  comment on  the following issue,
Please tell me whats your operating system and the version of the package and which package manager you are using?
https://github.com/ghodsizadeh/tehran-stocks/issues/1
