### ISSUE TITLE
گروه زراعت و خدمات وابسته

### ISSUE THREAD

**Issue by adaji** [ghodsizadeh/tehran-stocks#20]
من نتونستم اطلاعات گروه زراعت و خدمات وابسته رو بگیرم. احتمالا چون group_code این گروه 01 هست و فرمت این ستون int هست درست بازخوانی نمیشه اطلاعات. امیدوارم توی نسخه بعدی اصلاح بشه. در هر صورت عالی. ممنون

**Comment by ghodsizadeh** [comment]
میشه کدی که اجرا کردید و نتونستید نتیجه بگیرید رو اینجا ارسال کنید؟

**Comment by alidjmr** [comment]
pip3 install tehran_stocks_ng

python3

import tehran_stocks as ts
ts.get_all_price()

stock= ts.Stocks.query.filter_by(name='زکشت').first().df

برای سایر نمادهای گروه مثل سیمرغ زفکا زدشت و ... نیز به همین شکل. از روش‌های دیگر کوئری هم نتیجه مشابه است.

**Comment by ghodsizadeh** [comment]
بررسی می‌کنم.
برای نصب بهتره که از 
‍‍`pip3 install tehran_stocks`
استفاده کنید که نسخه تحت توسعه من هست.
بهتر که نه ولی من در مورد این نسخه می‌تونم پاسخگو باشم :)

**Comment by ghodsizadeh** [comment]
البته اشتباه از من بوده یک pull_request رو اشتباهی تایید کرده بودم 
در نتیجه فایل readme تغییر کرده بود.

**Comment by Pejhan** [comment]
به نظرم توی این مسئله ایراد از سایت tse هست چون برخی گروهها رو ظاهرن به روز نمیکنن یه نمونه ش کد گروه زراعت هست. همچنین هنوز نمیدونم چرا ولی نمادهای اختیار معامله و اخزا هم توی نمادهای دانلود شده نمیان.
را ه دیگه ای برای دانلود لیست نمادها نداریم؟ من یه مدت صفحه‌ی دیدبان بازار رو زیر نظر داشتم ولی اونم به نظرم چندان قابل اتکا نیست.
