### ISSUE TITLE
restriction based on the IP address

### ISSUE THREAD

**Issue by snima** [ghodsizadeh/tehran-stocks#21]
Hi, 
Is there any restriction based on the IP address to download data? (maybe inside and outside of Iran). 

Here is an example that I think the reason is the IP of the server that Jupiter is running on it: 
import tehran_stocks

from tehran_stocks import get_all_price, Stocks, update_group

get_all_price()

stock = Stocks.query.filter_by(name='كگل').first() #find by symbol(نماد)

stock.df 

Download Finished.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-825aab372293> in <module>
      8 stock = Stocks.query.filter_by(name='كگل').first() #find by symbol(نماد)
      9 
---> 10 stock.df

AttributeError: 'NoneType' object has no attribute 'df'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-210ff8d0e304> in <module>
----> 1 stock.summary()

AttributeError: 'NoneType' object has no attribute 'summary'

**Comment by ghodsizadeh** [comment]
Can you what is your OS? are you using Windows? 
I'll publish an update on Pypi this weekend, it will fix some bugs.

**Comment by snima** [comment]
OsX

**Comment by ghodsizadeh** [comment]
The functionality of the package is tested on Mac Osx. Maybe there is a (new)  restriction for IP addresses outside of Iran.
For now, I'm getting a 503 error from tsetmc.com when try to open it with a connected VPN.
I hope its a temporary problem, not a permanent restriction.
