### ISSUE TITLE
get_all_price() return error

### ISSUE THREAD

**Issue by Nixuri** [ghodsizadeh/tehran-stocks#22]
its working well but
get_all_price function return error

progress {100*int((i+1)/len(codes):.2f)}
---------------------------------------------------------------------------
InterfaceError                            Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1245                     self.dialect.do_execute(
-> 1246                         cursor, statement, parameters, context
   1247                     )

~/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    587     def do_execute(self, cursor, statement, parameters, context=None):
--> 588         cursor.execute(statement, parameters)
    589 

InterfaceError: Error binding parameter 0 - probably unsupported type.

The above exception was the direct cause of the following exception:

InterfaceError                            Traceback (most recent call last)
~/Documents/Code/Stock/stock.py in 
----> 1 get_all_price()

~/.local/lib/python3.6/site-packages/tehran_stocks/download/price.py in get_all_price()
     60     for i, code in enumerate(codes):
     61         print("progress {100*int((i+1)/len(codes):.2f)}")
---> 62         update_group(code)
     63 
     64     print("Download Finished.")

~/.local/lib/python3.6/site-packages/tehran_stocks/download/price.py in update_group(code)
     47     `Warning: Stock table should be updated`
     48     """
---> 49     stocks = db.session.query(Stocks.code).filter_by(group_code=code).all()
     50     if not stocks:
     51         print("Make sure group has some entity on Stocks")

~/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py in all(self)
   3231                 :ref:`faq_query_deduplicating`
   3232         """
-> 3233         return list(self)
   3234 
   3235     @_generative(_no_clauseelement_condition)

~/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py in __iter__(self)
   3387         if self._autoflush and not self._populate_existing:
   3388             self.session._autoflush()
-> 3389         return self._execute_and_instances(context)
   3390 
   3391     def __str__(self):

~/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py in _execute_and_instances(self, querycontext)
   3412         )
   3413 
-> 3414         result = conn.execute(querycontext.statement, self._params)
   3415         return loading.instances(querycontext.query, result, querycontext)
   3416 

~/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py in execute(self, object_, *multiparams, **params)
    980             raise exc.ObjectNotExecutableError(object_)
    981         else:
--> 982             return meth(self, multiparams, params)
    983 
    984     def _execute_function(self, func, multiparams, params):

~/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py in _execute_on_connection(self, connection, multiparams, params)
    291     def _execute_on_connection(self, connection, multiparams, params):
    292         if self.supports_execution:
--> 293             return connection._execute_clauseelement(self, multiparams, params)
    294         else:
    295             raise exc.ObjectNotExecutableError(self)

~/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_clauseelement(self, elem, multiparams, params)
   1099             distilled_params,
   1100             compiled_sql,
-> 1101             distilled_params,
   1102         )
   1103         if self._has_events or self.engine._has_events:

~/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1248         except BaseException as e:
   1249             self._handle_dbapi_exception(
-> 1250                 e, statement, parameters, cursor, context
   1251             )
   1252 

~/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1474                 util.raise_from_cause(newraise, exc_info)
   1475             elif should_wrap:
-> 1476                 util.raise_from_cause(sqlalchemy_exception, exc_info)
   1477             else:
   1478                 util.reraise(*exc_info)

~/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py in raise_from_cause(exception, exc_info)
    396     exc_type, exc_value, exc_tb = exc_info
    397     cause = exc_value if exc_value is not exception else None
--> 398     reraise(type(exception), exception, tb=exc_tb, cause=cause)
    399 
    400 

~/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    150             value.__cause__ = cause
    151         if value.__traceback__ is not tb:
--> 152             raise value.with_traceback(tb)
    153         raise value
    154 

~/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1244                 if not evt_handled:
   1245                     self.dialect.do_execute(
-> 1246                         cursor, statement, parameters, context
   1247                     )
   1248         except BaseException as e:

~/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    586 
    587     def do_execute(self, cursor, statement, parameters, context=None):
--> 588         cursor.execute(statement, parameters)
    589 
    590     def do_execute_no_params(self, cursor, statement, context=None):

InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT stocks.code AS stocks_code 
FROM stocks 
WHERE stocks.group_code = ?]
[parameters: ((10,),)]
(Background on this error at: http://sqlalche.me/e/rvf5)

**Comment by ghodsizadeh** [comment]
please install the latest version of the package 
```python
pip install --upgrade tehran-stocks```
and tell me if the error exists.
