### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Sabermou** [ghodsizadeh/tehran-stocks#23]
I run the code, but all the outputs are empty. It seems that no data is downloaded. For example I get the following output when I run the code about showing group names:

"Download Finished.
Make sure group has some entity on Stocks
[ ]"

Also when I print the data, It  shows that nothing has downloaded: 

"Empty DataFrame
Columns: [ ]
Index: [ ]"

Any idea about problem?

**Comment by farhadmpr** [comment]
I have the same problem.

**Comment by ghodsizadeh** [comment]
@Sabermou  
please upgrade the package with `pip install --upgrade terhan_stocks` and check if the problem exist or not.

**Comment by Sabermou** [comment]
@ghodsizadeh 
I got the following error:
Could not find a version that satisfies the requirement terhan_stocks (from versions: )
No matching distribution found for terhan_stocks.

By the way, Im not connecting from Iran, may it make a difference?

**Comment by ghodsizadeh** [comment]
no its because installation is incomplete. please try to install the package again.
`pip install --upgrade terhan_stocks `
