### ISSUE TITLE
Problem number of stock in Server 

### ISSUE THREAD

**Issue by alim7676** [ghodsizadeh/tehran-stocks#26]
**OS(vps): .** ubuntu 18 in germany
**OS(pc): .** Arch linux 
**python version: .** 3.6.9
Hey bro , i'm trying to updade stock price . In my pc `
len(stock_list) 
859
`
But in my vps the value is 357 !!!!
`
len(stock_list)
357
`

I dont have problem with price value they are update well but i need all 859 in stock_list. 
Sorry for my bad english .

**Comment by ghodsizadeh** [comment]
Can you explain more what's the problem? is there any problem with the initialization of the package?

**Comment by alim7676** [comment]
من توی سیستم خودم تعداد ۸۵۹ سهم رو داره و آپدیت میکنه اما سرور ۳۵۷ تا 
بی هیچ دلیلی یعنی هر دورو میزنم روی آپدیت تعداد اون استوک لیست و که میگیرم این تعدادن 
توی سرور بنظر میرسه کل سهم هارو نمیاره نمیدونم چطوری بهتر بگم

**Comment by alim7676** [comment]
الان که بیشتر بررسی کردم دقیقا تا گروه ۴۴ رو توی سرورم میاره فقط از ۹۰ تا گروه
حدود ۳۵۰ سهم

**Comment by alim7676** [comment]
Its solve by delete stock.db in tse folder and run again 

`
$ts-get init 
,
$ts-get update
`
