### ISSUE TITLE
قیمت ها یک روز عقب تر !!!

### ISSUE THREAD

**Issue by alim7676** [ghodsizadeh/tehran-stocks#27]
یک خسته نباشید بگم بابت پکیج خوبی که نوشتی 
یکی از اشکالات اینه قیمت ها یک روز عقبه و تا ۱۲ شبکه روز جدید بشه دسترسی یه قیمت های جدید نمیشه داشت . 

نیازه که اطلاعات هر سهم در همان روز شامل بازه قیمت، درصد تغییر قیمت ، اطلاعات حقیقی و حقوقی و .. هم قرار داده شود

**Comment by ghodsizadeh** [comment]
سلام متاسفانه فعلا از نظر فنی امکان اینکه زودتر به قیمت‌ها دسترسی داشته باشیم وجود نداره :(
