### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by mohammadrabetian** [ghodsizadeh/tehran-stocks#3]
installed with pip .
getting  No module named 'tehran_stocks' error when trying to import.
I also tried with different os but no luck.

**Comment by ghodsizadeh** [comment]
Can you send error-log? and tell me whats your os and what is your package manager(conda or pip)? 
And please check the following thread and tell me the result.
[https://github.com/ghodsizadeh/tehran-stocks/issues/3]

**Comment by mohammadrabetian** [comment]
ts-get with command line:

, line 6, in <module>
    import tehran_stocks as ts
ModuleNotFoundError: No module named 'tehran_stocks'

when importing in python :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tehran_stocks'
---------
I'm using pip .
and the package is installed, this is pip freeze log: 
numpy==1.17.0
pandas==0.25.0
python-dateutil==2.8.0
pytz==2019.1
six==1.12.0
SQLAlchemy==1.3.6
tehran-stocks==0.5.6
--------
I've tested with my Mac Os x and then I tested it with my Ubuntu os.. please note that I am doing these through python virtual env in both mentioned os.

**Comment by ghodsizadeh** [comment]
It seems its a new problem. I'll check it and tell you soon.

**Comment by mohammadrabetian** [comment]
I think it may have something to do with packaging.... I find the package when I manually copy the module inside my site packages.. maybe appending the package to sys path helps.. ?!
sys.path.append('/.../')

**Comment by ghodsizadeh** [comment]
Can you check with version `0.5.9`?
It seems it has a problem in the new packaging system which I introduce on version `0.5.6` ;)
I modified that system, and it seems it's working now.

**Comment by mohammadrabetian** [comment]
It's working now. Good job !
