### ISSUE TITLE
Error getting new data - date_shamsi 

### ISSUE THREAD

**Issue by BlackCrowxyz** [ghodsizadeh/tehran-stocks#30]
Hi,

After you have added the  **date_shamsi** feature, I couldn't update my dataFrame!
I also tried to upgrade my package, but it seems that the table in the database has no column for **date_shamsi**

Here is the code:
```
ticker_id = 35700344742885862
stock = Stocks.query.filter_by(code=str(ticker_id)).first()
stock.update()
```
the error:
```
(sqlalchemy.exc.OperationalError('(sqlite3.OperationalError) table stock_price has no column named date_shamsi'),
 '35700344742885862')
```
and df.tail() is not updated due that error: 

![SharedScreenshot](https://user-images.githubusercontent.com/31730646/77814281-37808e80-70cd-11ea-867b-76eafbd0b27c.jpg)

**_Thanks for making such a good python code, good luck. :)_**

**Comment by ghodsizadeh** [comment]
I'm not sure what's the reason I didn't test the package with an existing database and I think it's not compatible you can remove your database from $HOME/tse/stocks.db and then redownload your database or connect to the database and execute following code or something similar to it:
```python
from tehran_stocks import db
q = 'alter table price add column date_shamsi'
db.session.execute(q)
db.sesseion.commit()
```
you may need to debug the code to work but I think removing the database is easier and faster.
