### ISSUE TITLE
I cant update my package

### ISSUE THREAD

**Issue by faridkvi** [ghodsizadeh/tehran-stocks#31]
Hi guys,
I cant update my package.
when I write "ts-get update" on windows powershell, after about 2 seconds it replies "Download Finished." when i disconnect my internet it happens the same.

when I write "ts-get group 34" on windows powershell, it replies :
"Make sure group has some entity on Stocks
Done" when i disconnect my internet it happens the same.

 i did it in python but its not different.
can u help me?

**Comment by ghodsizadeh** [comment]
Can you share a screenshot of your python code and the error?
