### ISSUE TITLE
چرا همه گروه هارو نمیاره

### ISSUE THREAD

**Issue by kingtak66** [ghodsizadeh/tehran-stocks#32]
با سلام
من وقتی میخوام گروه هارو برام در بیاره فقط چند تاشو  نشون میده.در حالی کی باید حدود صد تا گروه که تو صفحه http://www.tsetmc.com/Loader.aspx?ParTree=111C1213 هست رو نشون بده برام

for r in Stocks.get_group():
    print(r)

#Output:
(10, 'استخراج زغال سنگ')
(11, 'استخراج نفت گاز و خدمات جنبي جز اکتشاف')
(13, 'استخراج کانه هاي فلزي')
(14, 'استخراج ساير معادن')
(17, 'منسوجات')
(19, 'دباغي، پرداخت چرم و ساخت انواع پاپوش')
(20, 'محصولات چوبي')
(21, 'محصولات كاغذي')
(22, 'انتشار، چاپ و تکثير')
(23, 'فراورده هاي نفتي، كك و سوخت هسته اي')
(25, 'لاستيك و پلاستيك')
(26, 'توليد محصولات كامپيوتري الكترونيكي ونوري')

**Comment by kingtak66** [comment]
اشتباه از من بود.دیتا کامل دانلود نشده بود.دیتابیس رو حذف کردم دوباره ایجاد کردم مشکل حل شد

**Comment by hashemiy66** [comment]
> اشتباه از من بود.دیتا کامل دانلود نشده بود.دیتابیس رو حذف کردم دوباره ایجاد کردم مشکل حل شد

دیتابیس رو چطوری پاک کردید؟
