### ISSUE TITLE
ذخیره هر سهم در یک فایل جدا

### ISSUE THREAD

**Issue by SaeidDowlati** [ghodsizadeh/tehran-stocks#33]
سلام
ممنون بابت پکیج مفیدی که به اشتراک گذاشتید.
 آیا راهی هست که تاریخچه قیمت هر سهم رو در یک فایل سی‌اس‌وی به طور جداگانه ذخیره کنیم؟
منظورم ذخیره اتوماتیک همه سهم‌ها با همه. به صورت تکی که مشکلی ندارم.

**Comment by ghodsizadeh** [comment]
بله میشه
کل جدول قیمت رو‌در پانداس بارگزاری کنید
بر اساس نام سهم گروه کنید و هر گروه رو ذخیره کنید.

**Comment by SaeidDowlati** [comment]
بله، ولی این روش وقت‌گیره. تعداد سهام هم زیاده.
منظورم روشیه که لیست اسامی و کدهای شرکت‌ها رو بهش بدیم و خودش هر کد رو تحت نام شرکت در یک فایل ذخیره کنه.

Name | Code

BMLT1 | 778253364357513
MOTX1 | 1931037287459550
SPAH1 | 2328862017676100
SSOX1 | 2819110578357790
TOSA1 | 2944500421562360
SKEX1 | 3037464497437280
LIRZ1 | 3149396562827130
DALX1 | 3362850293262740
SAKX1 | 3679885359158210
TAYD1 | 3722699128879020
MSKN1 | 3863538898378470

**Comment by ghodsizadeh** [comment]
نه متاسفانه این امکان وجود نداره و نیاز به دسترسی مستقیم به دیتابیس داره. 
اگر فکر می‌کنید ضروریه می‌تونید پکیج رو فورک کنید و این ویژگی رو به صورت پول ریکوئست بفرستید. در غیر این صورت توی لیست می‌ذارم و شاید در آینده خودم اضافه‌اش کنم.

**Comment by SaeidDowlati** [comment]
ممنون می‌شم اگه پکیج رو آپدیت کردید اینم مدنظرتون باشه.
مرسی از پاسختون
