### ISSUE TITLE
استخراج نام وکد و کد گروه برای یک سهم

### ISSUE THREAD

**Issue by jalal776** [ghodsizadeh/tehran-stocks#38]
سلام اقای قدسی زاده وقت بخیر
با تشکر بابت ماژول بورس تهران
سوالم اینه که چطور میشه به کل دیتابیس اصلی دسترسی داشت.

در واقع دنبال این هستم که نام سهام و کد سهم و کد گروه سهم رو از کل داده استخراج کنم

**Comment by ghodsizadeh** [comment]
سلام و درود همونطور که در راهنما توضیح داده شده با استفاده از دستور زیر می‌تونید به دیتابیس به صورت مستقیم دسترسی داشته باشی:

‍‍‍```
from tehran_stocks import Stocks, db

db.session.execute('select group_code , group_name from stocks group by group_name').fetchall()
```
