### ISSUE TITLE
Stocks آپدیت جدول

### ISSUE THREAD

**Issue by HamidMousavi** [ghodsizadeh/tehran-stocks#42]
با سلام
     آقای قدسی ز اده یکی از اشکالات پروژه که امروز متوجه شدم اینه که جدول نمادها
باید در هر آپدیت بروزرسانی بشه که نمیشه.مثلا فیلدهایی مثل : 
حجم مبنا،eps,p/e,...
درطول زمان تغییر میکنن و به نظرم بهتره همیشه بروز رسانی بشن.

دومین مشکل هم اینه که برنامه نمادهای دو گروه ۱,۲ رو نمیتونه از سایت دربیاره.  نمیدونم خودتون امتخان کردید یا نه؟
البته من توی سورسی که خودم باهاش کار میکنم یه متدی نوشتم که بتونه علاوه بر سایت بورس کدهای اضافی رو از فایل متنی که خودم اضافه میکنم بخونه و اطلاعاتشون رو در بیاره.ولی چون به نظرم راه حل اصولی نیست پول رکوئست ندادم.
این دوتا از مشکلاتیه که فکرمو درگیر کرده.شما چه راه حلی براشون دارید؟

**Comment by HamidMousavi** [comment]
جناب قدسی زاده یه راه دیگه واسه دانلود کد نمادها استفاده از دیدبان بازاره..توی دیدبان بازار تقریبا همه نمادها هستن.
از این لینک میشه فایل کد نمادهارو دریافت کرد.اینجوری دیگه مشکل گروه های 1 و 2 حل میشه
http://tsetmc.com/tsev2/data/MarketWatchPlus.aspx

**Comment by ghodsizadeh** [comment]
سلام من توی نسخه جدید یک راه جدید اضافه کردم که از یک جای مشخص دیتا رو بگیره.
برای همین این ایشو رو می‌بندم.
