### ISSUE TITLE
اضافه کردن قابلیت جدید به برنامه

### ISSUE THREAD

**Issue by eenvid** [ghodsizadeh/tehran-stocks#5]
سلام
همونطوری که میدونید برای نوشتن فیلتر توی سایت نیاز به تعداد و حجم، خرید و فروش، حقیقی و حقوقی هست
امکانش هست برای برنامه یک تابع جدید نوشت که این مقادیر رو در لحظه برای همه نمادها توی پایگاه داده ذخیره کنه؟؟

**Comment by ghodsizadeh** [comment]
سلام
ممنون میشم که لینک فضایی که این اطلاعات رو میده برای من بفرستید و به صورتی دقیق‌تر توضیح بدید چجوری اطلاعات رو میشه دریافت کرد.  تا امکان اضافه کردن این ویژگی رو بررسی کنم.

**Comment by jalalsadeghi** [comment]
سلام
فکر می کنم بخاطر اینکه اطلاعات رو از سایت بورس دانلود می کنیم، نمی تونیم به صورت لحظه ای قیمت ها و میزان خریداران حقیقی و حقوقی رو داشته باشیم .

`def get_stock_ids(group):
    url = "http://www.tsetmc.com/tsev2/data/InstValue.aspx?g={}&t=g&s=0"
    r = requests.get(url.format(group))
    ids = set(re.findall(r"\d{15,20}", r.text))
    return list(ids)`

برای گرفتن قیمت های لحظه ای حتما باید از سایت فرابورس وب سرویس خریداری کنیم.

متاسفانه در اغلب کشورها برای پیشرفت بورس کشورشون، وب سرویسها رو به صورت رایگان در اختیار عموم قرار میدهند. (در ایران برای این هم کیسه ای دوخته شده.)

**Comment by ghodsizadeh** [comment]
بنظرم امکان گرفتن قیمت لحظه‌ای از سایت بورس هم هست ولیکن باید با ترفند اینکار رو انجام بدیم.
ممنون بخاطر ایده اگر تونستم پیاده کنم حتما اطلاع می دم.
احتمالا در ویرگول و توییتر.

**Comment by amomehdi** [comment]
با استفاده از فرمول نویسی تو اکسل هم میتونید این کار رو انجام بدید
