### ISSUE TITLE
عدم دانلود اطلاعات و ایجاد نکردن آبجکت stock

### ISSUE THREAD

**Issue by saeedmie85** [ghodsizadeh/tehran-stocks#50]
my code is here:  for stock object can not find df atribiute

```
import tehran_stocks
from tehran_stocks import get_all_price, Stocks, update_group
get_all_price()
```
>  Download Finished.

```
from tehran_stocks import Stocks, db
stock = Stocks.query.filter_by(name='كگل').first() #find by symbol(نماد)
stock.df
```

>  Traceback (most recent call last):
> 
>       File "<ipython-input-9-7d2dff961c56>", line 1, in <module>
>         stock.df
> 
>       AttributeError: 'NoneType' object has no attribute 'df'
>

**Comment by farhadmpr** [comment]
I tested it but there was no problem

![Capture](https://user-images.githubusercontent.com/24851088/82124570-2262da80-97b5-11ea-9de6-660e77760188.JPG)

**Comment by saeedmie85** [comment]
> I tested it but there was no problem
> 
> ![Capture](https://user-images.githubusercontent.com/24851088/82124570-2262da80-97b5-11ea-9de6-660e77760188.JPG)

شما هم از آناکوندا استفاده می کنید؟ نمی دانم شاید بخاطر آناکوندا من این مشکل را دارم

**Comment by farhadmpr** [comment]
من از ipython استفاده کردم

**Comment by saeedmie85** [comment]
من این کد را در pycharm
هم امتحان کردم اما مشکل اینه که برای متغییر stock مقدار none  را بر میگرداند
`from tehran_stocks import Stocks, get_all_price
stock = Stocks.query.filter_by(code='35700344742885862').first() # find by code on tsetmc url
print(stock)
`

**Comment by HamidMousavi** [comment]
میشه بگید حجم فایل دیتا بیس تون چقدره؟

**Comment by saeedmie85** [comment]
من دیتابیس را نتونستم پیدا کنم 
فایلش کجا هست؟ خودمون که نیازی نیست دیتابیس خاصی ایجاد کنیم؟

**Comment by HamidMousavi** [comment]
نه لازم نیست دیتابیس ایجاد کنید.برنامه موقع اولین اجرا دیتابیس رو میسازه.
توی ویندوز 
C:\users\yourusername\tse\stocks.db

**Comment by saeedmie85** [comment]
حجم دیتا بیسم 24 کیلوبایت است

**Comment by HamidMousavi** [comment]
درست حدس زدم.مشکل شما به دلیل دانلود ناقص اطلاعاته.شما این فایل رو حذف کنید و برنامه رو دوباره اجرا کنید.

**Comment by saeedmie85** [comment]
خیلی ممنون حالا امتحان می کنم نتیجه را میگم

**Comment by saeedmie85** [comment]
خیلی ممنونم از کمکتون مشکل حل شد خیلی لطف کردین

**Comment by sqahremani419** [comment]
سلام.
جناب من فایل دیتا بیسم 34 مگ حجم داره.ولی خوب موقعی کمه دیتابیس رو باز میکنم با نرم افزار کلا 170 تا شرکت توش ثبت شده.یعنی همه شرکتای بورسی رو دانلود نکرده. اشکال از کجاست؟
