### ISSUE TITLE
دریافت اطلاعات شرکت های جدید اضافه شده در بورس

### ISSUE THREAD

**Issue by shayegh** [ghodsizadeh/tehran-stocks#51]
سلام
چجور میشه کد های جدیدی که بورس اضافه میشن را در یافت کرد؟
برای مثال من اطلاعات را قبل از ورود شستا به بورس دریافت کردم، الان با اینکه از 
update_group(39)
هم استفاد ه کردم باز هم اطلاعات شستا را بهم نشون نمی ده.
اصلا اطلاعاتش به بانک اطلاعاتی اضافه نمیشه!!

**Comment by shayegh** [comment]
من از کد زیر استفاده کردم
```python
for group in get_stock_groups():
    for stockid in get_stock_ids(group):
        print(f'stockid : {stockid}')
        # print(type(stockid))
        try:
            print(get_stock_detail(stockid,group))
        except:
            print(f'Error in Stock ID {stockid}')
```

**Comment by majid682008** [comment]
باید یه بار دیگه 
init
 بکنید تا 
DB
 آپدیت بشود و یا نماد‌ها حدید را به صورت دستی به 
DB
اضافه بکنید.
