### ISSUE TITLE
دیتافریم خالی 

### ISSUE THREAD

**Issue by abolfalk** [ghodsizadeh/tehran-stocks#55]
با سلام 
من کد ها رو به صورتکامل کپی می کنم و به درستی هم اجرا میشه ولی دیتا فریمی که به من میده خالی هست و به جز سطر عناوین مثل تاریخ و غیره چیز دیگه ای نداره
اگه میشه راهنمایی کنید
![Screenshot (43)](https://user-images.githubusercontent.com/66261730/83426226-15481b80-a444-11ea-8f08-37417ac8723f.png)

**Comment by smsajjadi** [comment]
من هم دچار این مشکل هستم. ظاهرا در گروه خودرویی این مشکل کلا هست. هنوز بقیه گروه ها رو تست نکردم ببینم چطور عمل می کنند

**Comment by abolfalk** [comment]
فایل دیتابیت رو پاک کن و دوباره برنامه رو ران کن درست میشه ولی مثل اینکه
گروه زراعی کلا مشکل دارن هیچ جوره نمیتونم درستشون کنم
