### ISSUE TITLE
Empty DataFrame

### ISSUE THREAD

**Issue by mrsazegar** [ghodsizadeh/tehran-stocks#57]
سلام روز بخیر 
من هم با اسم و هم با کد نماد تلاش کردم دیتا بگیرم اما دیتا فریم را به من خالی بر می گرداند . 
یکبار هم کل دیتابیس را پاک کردم و پروسه ی نصب را تکرار کردم اما اتفاق جدیدی نیافتاد . 
درون دیتابیس را که دیدم متوجه شدم که جدول
stock price 
هیچ مقداری داخلش نیست و عملا خالی است. حدس میزنم در مشکل در گرفتن دیتا از سایت باشد 
ممنون میشوم راهنمایی کنید 

با تشکر

**Comment by HamidMousavi-git** [comment]
سلام.
جدول استوک چی؟خالی که نیست؟
میتونید بگید چند تا رکورد  توی جدول استوکز دارید؟

**Comment by mrsazegar** [comment]
نه اون خالی نیست . و ۸۶۵ تا رکورد داخلش هست

**Comment by HamidMousavi** [comment]
وقتی دیتاهارو دانلود میکنید خطا نمیده؟
به نظرم جدیدا توی سایت بورس تهران یه تغییراتی دادن که این برنامه رو ربات تشخصی میده(که البته ربات هم هست. به خاطر اون اجازه دانلود دانلود قیمت ها رو نمیده>
)

در ماژول پرایس متد 
update_stock_price
لاین 
df = pd.read_csv(url.format(code))
رو پاک کنید و به جاش این کد رو بذارید.ببینید مشکلتون حل میشه؟


        headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
        req = requests.get(url, headers=headers)
        data = StringIO(req.text)
        df = pd.read_csv(data)

البته باید 
from io import StringIO 
رو هم توی همون ماژول پرایس ایمپورت کنید

**Comment by najafi82** [comment]
با سلام و عرض ادب
و تشکر بابت توسعه ماژول بورس تهران
آیا امکان دریافت قیمتهای تعدیل شده وجود دارد؟

**Comment by mrsazegar** [comment]
> وقتی دیتاهارو دانلود میکنید خطا نمیده؟
> به نظرم جدیدا توی سایت بورس تهران یه تغییراتی دادن که این برنامه رو ربات تشخصی میده(که البته ربات هم هست. به خاطر اون اجازه دانلود دانلود قیمت ها رو نمیده>
> )
> 
> در ماژول پرایس متد
> update_stock_price
> لاین
> df = pd.read_csv(url.format(code))
> رو پاک کنید و به جاش این کد رو بذارید.ببینید مشکلتون حل میشه؟
> 
> ```
>     headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
>     req = requests.get(url.format(code), headers=headers)
>     data = StringIO(req.text)
>     df = pd.read_csv(data)
> ```
> 
> البته باید
> from io import StringIO
> رو هم توی همون ماژول پرایس ایمپورت کنید
> 
> نتیجه رو به بگید ببینیم مشکلتون حل شده یا نه.

نه خطایی نمی گیرم در زمان دانلود . 
کد را هم جایگزین و امتحان کردم اما متاسفانه تغییری حاصل نشد

**Comment by PouyaAklion** [comment]
use `stock.update()` before `stock.df`

**Comment by mrsazegar** [comment]
> use `stock.update()` before `stock.df`

I also tried this. Still getting nothing, the DataFrame is empty.

**Comment by ghodsizadeh** [comment]
it's a known bug, most of time if you do what @PouyaAklion  said you should get the data, sometimes you have to restart the kernel because `sqlachemy` caches the previous result.
In next update I'll change the mechanism of communication with database.
