### ISSUE TITLE
افزایش سرمایه و تقسیم سود

### ISSUE THREAD

**Issue by bestheroforever** [ghodsizadeh/tehran-stocks#58]
چطور قیمت تعدیل شده سهام رو پیدا کنم؟

**Comment by ghodsizadeh** [comment]
سلام هنوز امکان مشاهده قیمت تعدیل شده سهام وجود نداره اگر امکانش پیدا شه در بروزرسانی عمده بعدی این ویژگی رو اضافه می‌کنم.
