### ISSUE TITLE
how to change db in mysql ?

### ISSUE THREAD

**Issue by sh4msi** [ghodsizadeh/tehran-stocks#6]
hi @ghodsizadeh

how to change db in mysql ?
Did you define a method for this?
Or do I have to manually change the original plugin codes?

**Comment by ghodsizadeh** [comment]
Hi,
For now, there is no way to change DB to MySQL, you have to change the package yourself.
There are two parts that you have to change. 
1- change the URI from SQLite to MySQL.
2- Change root/__init__.py where it checks the SQLite DB exists.
