### ISSUE TITLE
اضافه شدن اطلاعات جزیی روزهای گذشته

### ISSUE THREAD

**Issue by aliforoghi72** [ghodsizadeh/tehran-stocks#72]
سلام ابتا بابت زحمتی که کشیدید تشکر میکنم بسیار کد مفیدی هست
من نیاز دارم اطلاعات جزیی تره مثلا 3 روز گذشته رو داشته باشم
مثل حجم و تعداد خرید و فروش حقیقی و حقوقی
برای ای مین روز گذشته
ایا این اطلاعت رو میده؟ اگر جواب بله هست با چه کدی میتونم بدست بیارم؟
اگر نه هست ممنون میشم این رو هم اضافه کنید
من لینکشو میزارم براتون
http://cdn.tsetmc.com/History/46348559193224090/20211023
http://cdn.tsetmc.com/History/46348559193224090/20211020
http://cdn.tsetmc.com/History/46348559193224090/20211019

 یک درخواست دیگه هم ریز معاملات روز جاری هست که اطلاعات بسیار مهمی هست که چندین دوست دیگه هم تقاضا داشتن
و اینکه در لحظه بتونیم اطلاعات 5 ردیف تابلو رو داشته باشیم در بخش فروش خرید قیمت حجم تعداد 
اگر تعداد بیشتر رو نمایش بده که عالی میشه

**Comment by ghodsizadeh** [comment]
سلام ممنونم از شما.

متاسفانه مواردی که گفتید به دلایل فنی توی این پکیج قابلیت پیاده شدن نداره یا خیلی پیچیده‌اش می‌کنه. برای همین فعلا برنامه‌ای برای پیاده‌سازی این موارد ندارم. ولی اگر خودتون بتونید در این زمینه کمک کنید استقابل میشه.
